namespace KodieLingo.Model
{
    public class Lesson
    {
        // A lesson will be generated by the active pages' class based on user question response stats
        // A different lesson object will store the current data, (questions, etc) wheras this class
        // strictly marks the presence of a lesson within a topic.
        public int Id { get; set; }

        public int Difficulty { get; set; }
        public bool IsTest { get; set; } = false;
    }
}
